[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Solidity compiler settings for production
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
solc_version = "0.8.26"
evma = "paris"

[profile.ci]
optimizer = true
optimizer_runs = 1_000_000
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
